// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"example.com/go-yippi/internal/infrastructure/adapters/persistence/db/ent/product"
)

// ProductCreate is the builder for creating a Product entity.
type ProductCreate struct {
	config
	mutation *ProductMutation
	hooks    []Hook
}

// SetSku sets the "sku" field.
func (_c *ProductCreate) SetSku(v string) *ProductCreate {
	_c.mutation.SetSku(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *ProductCreate) SetSlug(v string) *ProductCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ProductCreate) SetName(v string) *ProductCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *ProductCreate) SetPrice(v float64) *ProductCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProductCreate) SetDescription(v string) *ProductCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ProductCreate) SetNillableDescription(v *string) *ProductCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *ProductCreate) SetWeight(v int) *ProductCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *ProductCreate) SetNillableWeight(v *int) *ProductCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetLength sets the "length" field.
func (_c *ProductCreate) SetLength(v int) *ProductCreate {
	_c.mutation.SetLength(v)
	return _c
}

// SetNillableLength sets the "length" field if the given value is not nil.
func (_c *ProductCreate) SetNillableLength(v *int) *ProductCreate {
	if v != nil {
		_c.SetLength(*v)
	}
	return _c
}

// SetWidth sets the "width" field.
func (_c *ProductCreate) SetWidth(v int) *ProductCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *ProductCreate) SetNillableWidth(v *int) *ProductCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *ProductCreate) SetHeight(v int) *ProductCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *ProductCreate) SetNillableHeight(v *int) *ProductCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProductCreate) SetStatus(v product.Status) *ProductCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProductCreate) SetNillableStatus(v *product.Status) *ProductCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProductCreate) SetCreatedAt(v time.Time) *ProductCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProductCreate) SetNillableCreatedAt(v *time.Time) *ProductCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProductCreate) SetUpdatedAt(v time.Time) *ProductCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProductCreate) SetNillableUpdatedAt(v *time.Time) *ProductCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ProductMutation object of the builder.
func (_c *ProductCreate) Mutation() *ProductMutation {
	return _c.mutation
}

// Save creates the Product in the database.
func (_c *ProductCreate) Save(ctx context.Context) (*Product, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProductCreate) SaveX(ctx context.Context) *Product {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProductCreate) defaults() {
	if _, ok := _c.mutation.Weight(); !ok {
		v := product.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.Length(); !ok {
		v := product.DefaultLength
		_c.mutation.SetLength(v)
	}
	if _, ok := _c.mutation.Width(); !ok {
		v := product.DefaultWidth
		_c.mutation.SetWidth(v)
	}
	if _, ok := _c.mutation.Height(); !ok {
		v := product.DefaultHeight
		_c.mutation.SetHeight(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := product.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := product.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := product.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProductCreate) check() error {
	if _, ok := _c.mutation.Sku(); !ok {
		return &ValidationError{Name: "sku", err: errors.New(`ent: missing required field "Product.sku"`)}
	}
	if v, ok := _c.mutation.Sku(); ok {
		if err := product.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "Product.sku": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Product.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := product.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Product.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Product.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Product.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Product.price"`)}
	}
	if v, ok := _c.mutation.Price(); ok {
		if err := product.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Product.price": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "Product.weight"`)}
	}
	if v, ok := _c.mutation.Weight(); ok {
		if err := product.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "Product.weight": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Length(); !ok {
		return &ValidationError{Name: "length", err: errors.New(`ent: missing required field "Product.length"`)}
	}
	if v, ok := _c.mutation.Length(); ok {
		if err := product.LengthValidator(v); err != nil {
			return &ValidationError{Name: "length", err: fmt.Errorf(`ent: validator failed for field "Product.length": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "Product.width"`)}
	}
	if v, ok := _c.mutation.Width(); ok {
		if err := product.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "Product.width": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "Product.height"`)}
	}
	if v, ok := _c.mutation.Height(); ok {
		if err := product.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "Product.height": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Product.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := product.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Product.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Product.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Product.updated_at"`)}
	}
	return nil
}

func (_c *ProductCreate) sqlSave(ctx context.Context) (*Product, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProductCreate) createSpec() (*Product, *sqlgraph.CreateSpec) {
	var (
		_node = &Product{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(product.Table, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Sku(); ok {
		_spec.SetField(product.FieldSku, field.TypeString, value)
		_node.Sku = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(product.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(product.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(product.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.Length(); ok {
		_spec.SetField(product.FieldLength, field.TypeInt, value)
		_node.Length = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(product.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(product.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(product.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(product.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ProductCreateBulk is the builder for creating many Product entities in bulk.
type ProductCreateBulk struct {
	config
	err      error
	builders []*ProductCreate
}

// Save creates the Product entities in the database.
func (_c *ProductCreateBulk) Save(ctx context.Context) ([]*Product, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Product, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProductCreateBulk) SaveX(ctx context.Context) []*Product {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
