// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"example.com/go-yippi/internal/infrastructure/adapters/persistence/db/ent/product"
	"example.com/go-yippi/internal/infrastructure/adapters/persistence/db/ent/user"
	"example.com/go-yippi/internal/infrastructure/adapters/persistence/db/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescSku is the schema descriptor for sku field.
	productDescSku := productFields[0].Descriptor()
	// product.SkuValidator is a validator for the "sku" field. It is called by the builders before save.
	product.SkuValidator = productDescSku.Validators[0].(func(string) error)
	// productDescSlug is the schema descriptor for slug field.
	productDescSlug := productFields[1].Descriptor()
	// product.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	product.SlugValidator = productDescSlug.Validators[0].(func(string) error)
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[2].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = productDescName.Validators[0].(func(string) error)
	// productDescPrice is the schema descriptor for price field.
	productDescPrice := productFields[3].Descriptor()
	// product.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	product.PriceValidator = productDescPrice.Validators[0].(func(float64) error)
	// productDescWeight is the schema descriptor for weight field.
	productDescWeight := productFields[5].Descriptor()
	// product.DefaultWeight holds the default value on creation for the weight field.
	product.DefaultWeight = productDescWeight.Default.(int)
	// product.WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	product.WeightValidator = productDescWeight.Validators[0].(func(int) error)
	// productDescLength is the schema descriptor for length field.
	productDescLength := productFields[6].Descriptor()
	// product.DefaultLength holds the default value on creation for the length field.
	product.DefaultLength = productDescLength.Default.(int)
	// product.LengthValidator is a validator for the "length" field. It is called by the builders before save.
	product.LengthValidator = productDescLength.Validators[0].(func(int) error)
	// productDescWidth is the schema descriptor for width field.
	productDescWidth := productFields[7].Descriptor()
	// product.DefaultWidth holds the default value on creation for the width field.
	product.DefaultWidth = productDescWidth.Default.(int)
	// product.WidthValidator is a validator for the "width" field. It is called by the builders before save.
	product.WidthValidator = productDescWidth.Validators[0].(func(int) error)
	// productDescHeight is the schema descriptor for height field.
	productDescHeight := productFields[8].Descriptor()
	// product.DefaultHeight holds the default value on creation for the height field.
	product.DefaultHeight = productDescHeight.Default.(int)
	// product.HeightValidator is a validator for the "height" field. It is called by the builders before save.
	product.HeightValidator = productDescHeight.Validators[0].(func(int) error)
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productFields[10].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	// productDescUpdatedAt is the schema descriptor for updated_at field.
	productDescUpdatedAt := productFields[11].Descriptor()
	// product.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	product.DefaultUpdatedAt = productDescUpdatedAt.Default.(func() time.Time)
	// product.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	product.UpdateDefaultUpdatedAt = productDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[0].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[3].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
}
